anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_token_manager = "vtmaopgPztD3WrNgYNrGFbtfUkcgVSxk6U8eycqQTPD"
cardinal_paid_claim_approver = "vpcKZrRAFr73Ty4W4bFM4xCWhxk1Whd9mHB1uuvFAKQ"
cardinal_time_invalidator = "vtiRVcPp7TjXUFgCwFGMDgKLZdbqY4dZJiWKYCv9Gb8"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'vpm5Gp95SYVyqwZz5zia5YsUNe7Kd6P7tFCC7GcXGbe'
cardinal_collateral_manager = 'vcmVnNNod8qTzr3n3WDkDSaSckJF9xYVU8hmtdSjWuX'

[programs.devnet]
cardinal_token_manager = "vtmaopgPztD3WrNgYNrGFbtfUkcgVSxk6U8eycqQTPD"
cardinal_paid_claim_approver = "vpcKZrRAFr73Ty4W4bFM4xCWhxk1Whd9mHB1uuvFAKQ"
cardinal_time_invalidator = "vtiRVcPp7TjXUFgCwFGMDgKLZdbqY4dZJiWKYCv9Gb8"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'vpm5Gp95SYVyqwZz5zia5YsUNe7Kd6P7tFCC7GcXGbe'
cardinal_collateral_manager = 'vcmVnNNod8qTzr3n3WDkDSaSckJF9xYVU8hmtdSjWuX'
